FROM node:5.12.0

ENV WORKDIR /usr/src/app
ENV NGINX_VERSION 1.10.1-1~jessie

RUN mkdir -p $WORKDIR \
  && apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 \
  && echo "deb http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get install --no-install-recommends --no-install-suggests -y \
            ca-certificates \
            nginx=${NGINX_VERSION} \
            nginx-module-xslt \
            nginx-module-geoip \
            nginx-module-image-filter \
            nginx-module-perl \
            nginx-module-njs \
            gettext-base \
  && rm -rf /var/lib/apt/lists/* \
  && ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

WORKDIR $WORKDIR

COPY package.json $WORKDIR
RUN npm install
COPY . $WORKDIR

EXPOSE 80 443

CMD ["/usr/src/app/start.sh"]