- name: test
  hosts: all

- name: prepare infra
  strategy: free
  hosts: app,api
  roles:
    - docker
  tags: [provision,docker]

- name: launch etcd
  hosts: etcd
  roles:
    - etcd
  tags: [provision,etcd]

- name: launch mongo
  hosts: db
  roles:
    - mongo
  tags: [provision,mongo]

- name: Run api
  hosts: api
  become: yes
  tasks:
    - name: run api
      docker:
        image: "{{ api_image }}"
        name: api
        pull: always
        detach: true
        env:
          DB_HOST: "{{ hostvars[groups['db'][0]]['ansible_default_ipv4']['address'] }}"
          DB_PORT: "{{ mongo_port }}"
          DB_NAME: "test"
        ports:
          - "{{ api_port }}:{{ api_port }}"
  tags: [deploy,api]

- name: Run app
  hosts: app
  # pre_tasks:
    # - debug: msg="{{ hostvars[groups['api'][0]]['inventory_hostname'] }}"
  tasks:
    - name: run app
      docker:
        image: "{{ app_image }}"
        name: app
        pull: always
        detach: true
        env:
          ENDPOINT: "{{ hostvars[groups['api'][0]]['inventory_hostname'] }}"
          ENDPOINT_PORT: "{{ api_port }}"
        ports:
          - "{{ app_port }}:{{ app_port }}"
  tags: [deploy,app]