- name: run container
  become: yes
  docker:
    image: "{{ etcd_image }}:v{{ etcd_version}}"
    name: etcd
    net: host
    pull: always
    detach: true
    volumes:
      - "{{ etcd_data_dir }}:{{ etcd_data_dir }}"
    ports:
      - "{{ etcd_client_port }}:{{ etcd_client_port }}"
      - "{{ etcd_server_port }}:{{ etcd_server_port }}"

- name: wait for etcd up and running
  uri:
    url: "{{ etcd_client_scheme }}://localhost:{{ etcd_client_port }}/health"
    status_code: 200
    return_content: yes
  register: health
  until: health.status is defined and health.status == 200
  retries: 30
  delay: 1
  delegate_to: "{{ inventory_hostname }}"
  ignore_errors: yes

- debug: msg="{{ health.content }}"
  when: health